openapi: 3.0.2
servers:
  - url: /v3
info:
  version: 1.0.0
  title: Crawl Owl schema
tags:
  - name: task
    description: Task operations
paths:
  /tasks:
    post:
      tags:
        - task
      summary: Add a new task
      description: Add a new task
      operationId: addTask
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
      requestBody:
        description: Create a new task
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
  '/tasks/{taskId}':
    get:
      tags:
        - task
      summary: Find task by ID
      description: Returns a single task
      operationId: getTaskById
      parameters:
        - name: taskId
          in: path
          description: ID of task to return
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: Task not found
    post:
      tags:
        - task
      summary: Updates a task
      description: ''
      operationId: updateTask
      parameters:
        - name: taskId
          in: path
          description: ID of task that needs to be updated
          required: true
          schema:
            type: string
            format: uuid
        - name: site_url
          in: query
          description: Site URL of task that needs to be updated
          schema:
            type: string
        - name: condition
          in: query
          description: Condition of task that needs to be updated
          schema:
            type: string
        - name: duration_day
          in: query
          description: Duration day of task that needs to be updated
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: successful operation
components:
  schemas:
    Task:
      required:
        - site_url
        - condition
        - duration_day
      properties:
        id:
          type: string
          format: uuid
        site_url:
          type: string
          format: uri
        condition:
          type: string
        duration_day:
          type: integer
          format: int32
      type: object
