// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// AddTask implements addTask operation.
//
// Add a new task.
//
// POST /tasks
func (UnimplementedHandler) AddTask(ctx context.Context, req *Task) (r *Task, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTaskById implements getTaskById operation.
//
// Returns a single task.
//
// GET /tasks/{taskId}
func (UnimplementedHandler) GetTaskById(ctx context.Context, params GetTaskByIdParams) (r GetTaskByIdRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateTask implements updateTask operation.
//
// Updates a task.
//
// POST /tasks/{taskId}
func (UnimplementedHandler) UpdateTask(ctx context.Context, params UpdateTaskParams) error {
	return ht.ErrNotImplemented
}
