// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// AddTask implements addTask operation.
	//
	// Add a new task.
	//
	// POST /tasks
	AddTask(ctx context.Context, req *Task) (*Task, error)
	// GetTaskById implements getTaskById operation.
	//
	// Returns a single task.
	//
	// GET /tasks/{taskId}
	GetTaskById(ctx context.Context, params GetTaskByIdParams) (GetTaskByIdRes, error)
	// UpdateTask implements updateTask operation.
	//
	// Updates a task.
	//
	// POST /tasks/{taskId}
	UpdateTask(ctx context.Context, params UpdateTaskParams) error
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
