// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// DeleteTasksTaskId implements delete-tasks-taskId operation.
//
// Your DELETE endpoint.
//
// DELETE /tasks/{taskId}
func (UnimplementedHandler) DeleteTasksTaskId(ctx context.Context, params DeleteTasksTaskIdParams) error {
	return ht.ErrNotImplemented
}

// GetTasks implements get-tasks operation.
//
// Your GET endpoint.
//
// GET /tasks
func (UnimplementedHandler) GetTasks(ctx context.Context) (r []Task, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTasksTaskId implements get-tasks-taskId operation.
//
// Your GET endpoint.
//
// GET /tasks/{taskId}
func (UnimplementedHandler) GetTasksTaskId(ctx context.Context, params GetTasksTaskIdParams) (r GetTasksTaskIdRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PostTasks implements post-tasks operation.
//
// Your POST endpoint.
//
// POST /tasks
func (UnimplementedHandler) PostTasks(ctx context.Context, req OptTask) (r *Task, _ error) {
	return r, ht.ErrNotImplemented
}
