// Code generated by ogen, DO NOT EDIT.
package api

type CrateTaskRes interface {
	crateTaskRes()
}

type DeleteTaskByIDRes interface {
	deleteTaskByIDRes()
}

type GetTaskByIDRes interface {
	getTaskByIDRes()
}

type GetTasksRes interface {
	getTasksRes()
}
