openapi: 3.1.0
x-stoplight:
  id: malmoc95sulph
info:
  title: main
  version: '1.0'
  contact:
    url: placeholder
    name: placeholder
    email: asdf@example.com
  description: description
  license:
    name: None
    url: 'https://example.com/terms'
  termsOfService: 'https://example.com/terms'
servers:
  - url: 'http://localhost:8080'
paths:
  /tasks:
    get:
      summary: Get Tasks
      tags:
        - task
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TaskResponse'
                  x-stoplight:
                    id: esye4wsv4xev0
      operationId: get-tasks
      x-stoplight:
        id: 9q6rfd0mb8rqm
      parameters: []
      description: Get Tasks
    post:
      summary: Create Task
      tags:
        - task
      responses:
        '201':
          description: Created
      operationId: crate-task
      x-stoplight:
        id: v83ljt82n8yl2
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskRequest'
        description: ''
      description: Create Task
  '/tasks/{taskId}':
    parameters:
      - schema:
          type: string
          format: uuid
        name: taskId
        in: path
        required: true
        description: Task ID
    get:
      summary: Get Task by ID
      tags:
        - task
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskResponse'
        '404':
          description: Not Found
      operationId: get-task-by-id
      x-stoplight:
        id: d6ogw1upatj59
      parameters: []
      description: Get Task by ID
    delete:
      summary: Delete Task by ID
      tags:
        - task
      responses:
        '200':
          description: OK
      operationId: delete-task-by-id
      x-stoplight:
        id: wheqz161eflx2
      parameters: []
      description: Delete Task by ID
components:
  schemas:
    TaskCore:
      title: TaskCore
      x-stoplight:
        id: ka2mtvt3r48ep
      type: object
      required:
        - site_url
        - duration_day
        - condition_query
        - is_public
      properties:
        site_url:
          type: string
          x-stoplight:
            id: j4mv6zri6irqd
          format: uri
          maxLength: 100
        duration_day:
          type: integer
          x-stoplight:
            id: cf4tf4eq87fev
          minimum: 1
        condition_query:
          type: string
          x-stoplight:
            id: rdr3rv3qtyyey
        is_public:
          type: boolean
          x-stoplight:
            id: bqyb42m4ln87o
      description: ''
    TaskRequest:
      title: TaskRequest
      x-stoplight:
        id: qrvfcxh96beae
      allOf:
        - $ref: '#/components/schemas/TaskCore'
      description: ''
    TaskResponse:
      title: TaskResponse
      x-stoplight:
        id: y3molyyrjkysg
      allOf:
        - $ref: '#/components/schemas/TaskCore'
        - type: object
          x-stoplight:
            id: jonqvnq2o336n
          required:
            - id
            - created_at
            - created_by
            - updated_at
          properties:
            id:
              type: string
              x-stoplight:
                id: nejingc8829rp
              format: uuid
              readOnly: true
            created_at:
              type: string
              x-stoplight:
                id: 9yt0u7yv8pkxa
              format: date-time
              readOnly: true
            created_by:
              type: string
              x-stoplight:
                id: hw98mzufjrgxa
              format: uuid
              readOnly: true
            updated_at:
              type: string
              x-stoplight:
                id: r36pi4dy0p6wh
              format: date-time
              readOnly: true
      description: ''
  requestBodies: {}
  responses: {}
tags:
  - name: task
    description: task
